project:
  type: book

book:
  favicon: favicon.png
  title: "Podstawy programowania w R"
  author: "Łukasz Wawrowski"
  date: ""
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-struktury.qmd
    - 03-przetwarzanie.qmd
    - 04-wizualizacja.qmd
    - 05-programowanie.qmd
    - 06-testy.qmd

format:
  html:
    theme: cosmo
    toc-title: "Spis treści"
